spring:
  application:
    name: selab12306-user-servicea
  datasource:
    url:
    driver-class-name:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      username: nacos
      password: nacos
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
